language: go
go:
- 1.5.1
- tip
before_install:
  - rvm install 2.2.3
  - nvm install 5.5
install:
- ./ci/install-hugo.sh
- npm install
script:
- npm test
- npm run build
env:
  - SITE_BASEURL_PRODUCTION="https://ffd-microsite-production.app.cloud.gov/" SITE_BASEURL_STAGING="https://ffd-microsite-staging.app.cloud.gov/"
deploy:
  - provider: cloudfoundry
    api: https://api.fr.cloud.gov
    username: fdf55389-2c59-47aa-83a0-bc812eb5b1fb
    password:
      secure: "J3JX0fCbYSM6kFoHyJy+WFULYGaqcqI/Tmxm8Ym691oU+hfDrRWylMyjnHUWOzzVsuSQeVcIPb6lpQuhYs1Key1e3xefDQVUn9z6izH+vgAr9KRnWU+QyZ6pSEpo8wzfdbMStbNVM/egTX0HtZqj251AUuw6V44DTq9NYw6IWFvyroT6RqVLuubQBzQIbbbUKDOLGyxHmvgG60uHPAZ4HGmuHkZy4z/qXmARhsmP5j9VfFsxxnBkxFzJnozmq8nQ06VnittED0qxz+0e/HJs7bjlK9Gm/BRo6uvK01qXtAvbi8rczqZCm/nGyuWnNGfMXrkrVvMHq52xfFgJRsnrOE0zUHRVDofKRkK6Wg4AXsqv2qGaaYBQF5MEB7ewvm6TLYh9+cgHvbFye8GTVx0CBkMewlk+8BZjr39UXAZu3uHO/bAdz7C4O5BSTm77fIb66T8hy0AtTfNbGF2/AEAH1jG3gN4Q+kPtBVlFxG69GnLUjGGjPoC1RdE/MsANwhPI6EKBkYnKTF4U1F6RdSnfQ/ftZlRU0ulj3wAFlrrcTMbZiYNKa/4gduUGxm3cy5CiEkHQyKg5x3e+F065D6w9ZxXgrRvgf7p7Orlh2d8PPKcoap9ny0wOPDVJDQ7/uPQ7k0vO1UHOBIvpxG2Vegsgh+Pn12kDCo+be5UQSccIQZ8="
    organization: gsa-opp-ffd
    space: microsite-staging
    on:
      repo: 18F/ffd-microsite
      branch: staging
  - provider: cloudfoundry
    api: https://api.fr.cloud.gov
    username: fdf55389-2c59-47aa-83a0-bc812eb5b1fb
    password:
      secure: "J3JX0fCbYSM6kFoHyJy+WFULYGaqcqI/Tmxm8Ym691oU+hfDrRWylMyjnHUWOzzVsuSQeVcIPb6lpQuhYs1Key1e3xefDQVUn9z6izH+vgAr9KRnWU+QyZ6pSEpo8wzfdbMStbNVM/egTX0HtZqj251AUuw6V44DTq9NYw6IWFvyroT6RqVLuubQBzQIbbbUKDOLGyxHmvgG60uHPAZ4HGmuHkZy4z/qXmARhsmP5j9VfFsxxnBkxFzJnozmq8nQ06VnittED0qxz+0e/HJs7bjlK9Gm/BRo6uvK01qXtAvbi8rczqZCm/nGyuWnNGfMXrkrVvMHq52xfFgJRsnrOE0zUHRVDofKRkK6Wg4AXsqv2qGaaYBQF5MEB7ewvm6TLYh9+cgHvbFye8GTVx0CBkMewlk+8BZjr39UXAZu3uHO/bAdz7C4O5BSTm77fIb66T8hy0AtTfNbGF2/AEAH1jG3gN4Q+kPtBVlFxG69GnLUjGGjPoC1RdE/MsANwhPI6EKBkYnKTF4U1F6RdSnfQ/ftZlRU0ulj3wAFlrrcTMbZiYNKa/4gduUGxm3cy5CiEkHQyKg5x3e+F065D6w9ZxXgrRvgf7p7Orlh2d8PPKcoap9ny0wOPDVJDQ7/uPQ7k0vO1UHOBIvpxG2Vegsgh+Pn12kDCo+be5UQSccIQZ8="
    organization: gsa-opp-ffd
    space: microsite-production
    on:
      repo: 18F/ffd-microsite
      branch: master
